### ISSUE TITLE
Further Information

### ISSUE THREAD

**Issue by trongtai37** [MinhasKamal/TrojanCockroach#12]
I have read your open source about this spyware.
Thank you very much !
The code is clear and helpful.
Can you show me the open source of the file Transmit.exe, you can update to the project, can't you ?

**Comment by MinhasKamal** [comment]
ref: https://github.com/MinhasKamal/TrojanCockroach/issues/10

**Comment by trongtai37** [comment]
Thank you for you support 👍

**Comment by trongtai37** [comment]
I remove the "return; // :)" in the code and compile it normally.
But When i run the TrojanCockroach.exe and plug my USB, there's nothing happen to my USB (no new folder or shortcut).
Anybody have the same problem ?

**Comment by trongtai37** [comment]
@MinhasKamal can you tell me how to create a shortcut of trojanCockroach like you do ?

**Comment by MinhasKamal** [comment]
this might help- https://www.computerhope.com/issues/ch000739.htm

**Comment by ariflimbong** [comment]
> I remove the "return; // :)" in the code and compile it normally.
> But When i run the TrojanCockroach.exe and plug my USB, there's nothing happen to my USB (no new folder or shortcut).
> Anybody have the same problem ? @MinhasKamal Could u help me, pls ?

me too..do you still stuck at it now?

**Comment by Rezureaxx** [comment]
> > I remove the "return; // :)" in the code and compile it normally.
> > But When i run the TrojanCockroach.exe and plug my USB, there's nothing happen to my USB (no new folder or shortcut).
> > Anybody have the same problem ? @MinhasKamal Could u help me, pls ?
> 
> me too..do you still stuck at it now?

Hey!Did you find a solution?
