### ISSUE TITLE
Infect.lnk does not copy itself

### ISSUE THREAD

**Issue by Shahrukh95** [MinhasKamal/TrojanCockroach#3]
I compiled all the cpps and placed all the files in one folder as shown in the pictures. Then I ran trojancockroach.exe. In the USB drive I can see one folder named "TrojanCockroach" but I do not see any other file besides that (the shortcut is missing).

Another issue is that the shortcut "trojancockroach.lnk" does not copy itself to the startup folder.

I am using Windows 7 in VMware to test this program.

**Comment by mastersuv** [comment]
As of 10/28/17 1:34 AM, everything is working as explained by the author.
It took me a long time... but eventually the code started to make sense and debugging became easier.

Finally I can go to sleep with peace of mind, but not before "washing my hands".
Can't wait to test the infection process later today.

@MinhasKamal I always wondered how this kind of infection worked, and this helped me understand. Thx man.

**Comment by trongtai37** [comment]
> I compiled all the cpps and placed all the files in one folder as shown in the pictures. Then I ran trojancockroach.exe. In the USB drive I can see one folder named "TrojanCockroach" but I do not see any other file besides that (the shortcut is missing).
> 
> Another issue is that the shortcut "trojancockroach.lnk" does not copy itself to the startup folder.
> 
> I am using Windows 7 in VMware to test this program.

I have the same problem. T think the anti-virus program delete the shortcut !
