### ISSUE TITLE
Infection of the system itself

### ISSUE THREAD

**Issue by Dagdelo** [MinhasKamal/TrojanCockroach#7]
After running TrojanCockroach.exe my PC has infected. After the fixes. When you run TrojanCockroach.exe the computer becomes infected along with the USB drive.
Is this behavior normal? I thought I'd open a prompt waiting for a removable drive.

**Comment by MinhasKamal** [comment]
This is completely normal. Here the thing is- if anyone inserts USB Drive into your computer, he gets infected too :)
